version: '3.3'
services:
  grafana:
    image: 'grafana/grafana'
    ports:
      - '3000:3000'
    volumes: 
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SERVER_ROOT_URL=http://grafana.server.name
      - GF_SECURITY_ADMIN_PASSWORD=secret
  prometheus:
    image: prom/prometheus:v2.1.0
    ports:
      - '9090:9090'
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    ports:
      - '9100:9100'
volumes:
  prometheus_data: {}
  grafana_data: {}
